version: '3'

services:
  api:
    image: node:fermium-alpine
    command: npm run start
    depends_on:
     - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - contacts_network

  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    networks:
      - contacts_network

networks:
  contacts_network: